baseURL = "/"
languageCode = "en-us"
title = "Dev's Blogging"
theme = "theme1"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@mahadev__k"
  cloudinary_url = "https://res.cloudinary.com/mahadevspace"

  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false

  addFrame = true
  addDot = true

  highlightColor = '#001644'


[markup]
  [markup.goldmark.renderer]
      unsafe = true